=== StefanRamadanovic/NRT_58_19/oglasi.dtd
<!ELEMENT oglasi (oglas+)>
<!ELEMENT oglas (kategorija, datumIsteka, cena, tekstOglasa, oznaka+, ePosta+)>
<!ELEMENT kategorija (#PCDATA)>
<!ELEMENT datumIsteka (dan, mesec, godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekstOglasa (#PCDATA)>
<!ELEMENT oznaka (#PCDATA)>
<!ELEMENT ePosta (#PCDATA)>
<!ATTLIST cena valuta (eur | din) "din">
<!ATTLIST ePosta tip (privatni | javni) #IMPLIED>

=== StefanRamadanovic/NRT_58_19/oglasi.xml
<?xml version="1.0" encoding="UTF-8" standalone = "no"?>
<!DOCTYPE oglasi SYSTEM "oglasi.dtd">
<oglasi>
    <oglas>
        <kategorija>Automobili</kategorija>
        <datumIsteka>
            <dan>10</dan>
            <mesec>10</mesec>
            <godina>2022</godina>
        </datumIsteka>
        <cena valuta="eur">1000</cena>
        <tekstOglasa>Ovo je oglas o automobilu</tekstOglasa>
        <oznake>
            <oznaka>Kao nov</oznaka>
            <oznaka>Bez problema</oznaka>
        </oznake>
        <ePosta tip="privatni">Stefan@gmail.com</ePosta>
    </oglas>
        <oglas>
        <kategorija>Stan</kategorija>
        <datumIsteka>
            <dan>12</dan>
            <mesec>12</mesec>
            <godina>2022</godina>
        </datumIsteka>
        <cena valuta="eur">5000</cena>
        <tekstOglasa>Ovo je oglas o stanu</tekstOglasa>
        <oznake>
            <oznaka>Kao nov</oznaka>
            <oznaka>Bez problema</oznaka>
        </oznake>
        <ePosta tip="javni">Igor@gmail.com</ePosta>
    </oglas>
    <oglas>
        <kategorija>Alat</kategorija>
                <datumIsteka>
            <dan>11</dan>
            <mesec>11</mesec>
            <godina>2022</godina>
        </datumIsteka>
        <cena valuta="din">500</cena>
        <tekstOglasa>Ovo je oglas o alatu</tekstOglasa>
        <oznake>
            <oznaka>Korisceno</oznaka>
        </oznake>
        <ePosta tip="privatni">Petar@gmail.com</ePosta>
        <ePosta tip="privatni">Petar@business.mail.com</ePosta>
    </oglas>
</oglasi>
